### ISSUE TITLE
Not working over ssh

### ISSUE THREAD

**Issue by juanolon** [imbue-ai/jupyter_ascending#47]
Hello,
I'm trying to execute jupyter_ascending over ssh (as showed on the readme), but it doesn't seem to work. It does work locally thou.

I connect with the following command to the server `ssh -L 8888:127.0.0.1:8080 user@ip` and start the jupyter server like

```
JUPYTER_ASCENDING_EXECUTE_PORT=8080 jupyter notebook --port 8080
[I 13:54:54.964 NotebookApp] LOADING JUPYTER ASCENDING SERVER PLUGIN

```

The error I get when trying to execute a cell on the editor
```
2022-12-28T13:55:14.143776+0000 - Unable to find a paired notebook for /home/juanolon/uni/master/LSTMandRNs/ex3/A3.sync.py in registered notebooks: {}.
Either a properly named notebook (ending in .sync.ipynb) is not running, or it didn't register properly for some reason.
{"jsonrpc": "2.0", "result": {"success": false, "error": "Unable to find a paired notebook for /home/juanolon/uni/master/LSTMandRNs/ex3/A3.sync.py in registered notebooks: {}.\nEither a properly named notebook (ending in .sync.ipynb) is not running, or it didn't register properly for some reason."}, "id": 1}
{"jsonrpc": "2.0", "method": "perform_notebook_request", "params": {"command_name": "ExecuteRequest", "notebook_path": "/home/juanolon/uni/master/LSTMandRNs/ex3/A3.sync.py", "data": {"file_name": "/home/juanolon/uni/master/LSTMandRNs/ex3/A3.sync.py", "cell_index": 1, "contents": ""}}, "id": 1}

```

Jupyter ascending seems to be correctly installed on the server
```
jupyter serverextension list
Known nbextensions:
  config dir: /usr/local/share/miniconda/etc/jupyter/nbconfig
    notebook section
      jupytext/index  enabled 
      - Validating: OK
      jupyter_ascending/extension  enabled 
      - Validating: OK

```
```
jupyter serverextension list
config dir: /usr/local/share/miniconda/etc/jupyter
    jupyterlab  enabled 
    - Validating...
      jupyterlab 3.5.2 OK
    jupytext  enabled 
    - Validating...
      jupytext 1.14.4 OK
    jupyter_ascending  enabled 
    - Validating...
      jupyter_ascending 0.1.24 OK
```

My first assumption was the absolute path on the jsonrpc request, so i tested to create the same folder structure on the server. same error..

Any ideas?

Thanks!

**Comment by micimize** [comment]
Hmm – I wonder if it's actually successfully starting on `8080` or if it ended up [retrying](https://github.com/untitled-ai/jupyter_ascending#working-with-multiple-jupyter-servers-or-alternate-ports)? Seems like a bigger error would be thrown in that case though so might require a bit more investigation.

Can you look at the list of running notebooks? And maybe 2x check that there aren't 2 notebook servers running?
![image](https://user-images.githubusercontent.com/8343799/211106985-54fadd72-8049-4b5c-a857-3f4996d12cc2.png)

**Comment by ajyl** [comment]
Hmm, I'm seeing almost the exact same behavior! There are no other notebooks running. 

For what it's worth, when running Jupyter notebook, the server will say something like 
```
copy and paste one of these URLs:
        http://localhost:8888/?token=0559f39031973b8589ebd2d8695c86563d016cfd63947422
```

And when I do, I get a 302 response:
```
[I 16:25:22.831 NotebookApp] 302 GET /?token=0559f39031973b8589ebd2d8695c86563d016cfd63947422 (127.0.0.1) 1.930000ms
```
and get redirected to `/tree` -- something that I won't see when working locally but happens when I work via ssh...

**Comment by joshalbrecht** [comment]
Hmmm... looking at the original post, I see:
```
JUPYTER_ASCENDING_EXECUTE_PORT=8080 jupyter notebook --port 8080
```

What if you try without anything about those special ports and just try this instead:

```
jupyter notebook
```

Does it work then?  You'll need to SSH forward to the actual port it binds, which is 8888 by default I believe.

And if not--what versions of things are you running? Here's what I have (not sure if all are relevant but figured I'd past them all):

```
jupyter==1.0.0
jupyter-ascending==0.1.23
jupyter-console==6.6.3
jupyter-events==0.6.3
jupyter_client==8.0.3
jupyter_core==5.2.0
jupyter_server==2.4.0
jupyter_server_terminals==0.4.4
jupyterlab-widgets==1.1.2
```

**Comment by juanolon** [comment]
Hey ppl.
a bit late to the party, but what it did worked for me was having exactly the same version of jupyter and jupyter-ascending on both ends. then it works without any complication.
